---
title: "Lectura de datos ordenados"
format: html
editor: visual
---

```{r}
download.file("https://raw.githubusercontent.com/rse-r/intro-programacion/main/datos/metadatos_completos.csv", "datos/metadatos.csv")
download.file("https://raw.githubusercontent.com/rse-r/intro-programacion/main/datos/NH0472.csv", "datos/estacion-NH0472.csv")
download.file("https://raw.githubusercontent.com/rse-r/intro-programacion/main/datos/NH0910.csv", "datos/estacion-NH0910.csv")
download.file("https://raw.githubusercontent.com/rse-r/intro-programacion/main/datos/NH0046.csv", "datos/estacion-NH0046.csv")
download.file("https://raw.githubusercontent.com/rse-r/intro-programacion/main/datos/NH0098.csv", "datos/estacion-NH0098.csv")
download.file("https://raw.githubusercontent.com/rse-r/intro-programacion/main/datos/NH0437.csv", "datos/estacion-NH0437.csv")
```

```{r}
metadatos <- read.csv("datos/metadatos.csv")
estacion_NH0472 <- read.csv("datos/estacion-NH0472.csv")
estacion_NH0910 <- read.csv("datos/estacion-NH0910.csv")
estacion_NH0046 <- read.csv("datos/estacion-NH0046.csv")
estacion_NH0098 <- read.csv("datos/estacion-NH0098.csv")
estacion_NH0437 <- read.csv("datos/estacion-NH0437.csv")
```

```{r}
library(dplyr)
```

```{r}
glimpse(metadatos)
glimpse(estacion_NH0046)
glimpse(estacion_NH0098)
glimpse(estacion_NH0472)
glimpse(estacion_NH0910)
glimpse(estacion_NH0437)
```
